plexinc/plex-for-kodi

lib/_included_packages/plexnet/asyncadapter.py

When opening the Plex add-on it hung on the loading screen for a while and then went to the home screen saying no servers could be found. I looked at the kodi.log file and found the error below, and it looks like adding the new keyword argument 'request_context' to _new_pool fixed the problem.  
NOTICE: script.plex: API: ERROR: Request failed https://plex.tv/users/sign_in.xml?X-Plex-Token=**** - _new_pool() got an unexpected keyword argument 'request_context'

Fixed requests not being able to be completed

---

addon.xml

This loads the background service, that auto-launches the Plex addon after profile login, not Kodi startup.
This way autostart works with multi profile setups as well.

Kiosk mode fix when profile switching is enabled

---

lib/util.py
lib/windows/seekdialog.py

Fixes the displayed end-time of a video to be properly formatted in the user's chosen 24/12h time format, based on Kodi settings.

fully fix #90

---

lib/windows/kodigui.py
lib/windows/search.py

GHI (If applicable): #174
Currently the discovery/search window is only exitable using the search/discovery button itself. ACTION_PREVIOUS_MENU (in my case, the key `ESCAPE`) doesn't do that.
Also fixes an exception which was reproducable due to wrong usage of the rpc version response.

Exit discovery/search using ACTION_PREVIOUS_MENU (ESCAPE) even while the search field has focus

---

lib/windows/home.py

GHI (If applicable): #177
When continuing to scroll right on a hub item list, triggering a pagination load, multiple tasks with possibly the same hub offset values are queued. This leads to duplicate pagination results.
This PR attempts to fix that by checking whether a hub item list pagination task is already queued and throws the subsequent calls away.

home hub: don't queue multiple hub item list pagination threads while one is active

---

lib/windows/episodes.py
lib/windows/opener.py
lib/windows/preplay.py

GHI (If applicable): #5
This is a follow-up to PR #184 with a cleaner auto play approach for episodes. It now uses the `EpisodesWindow` for auto play of episodes instead of the `PrePlayWindow`. Post-play-behaviour should be as expected now.

Improve auto play from home handling for episodes

---

lib/player.py
lib/util.py
lib/windows/seekdialog.py
resources/language/English/strings.po
resources/language/German/strings.po
resources/settings.xml
resources/skins/Main/1080i/script-plex-seek_dialog.xml

- try instantly hiding the OSD after a video has been resumed (depending on the skin and optionally the skinhelperservice) #172 
- using the left/right buttons without any OSD shown now do skipping (30/-10) instead of showing the OSD and seeking on the timeline
- skipping without an OSD shown now properly visually indicated
- automatically apply the currently selected seeking from the timeline after a 1 second delay
- increase the delay after which a skipping gets applied from 0.5s to 1s
- visually indicate negative seeking by adjusting the timeline dynamically #181
- auto-pause after seeking/skipping if the seek/skip was done when the video was paused instead of instantly resuming
- add addon setting for using configured kodi skip steps instead of 30/-10 #133

Seeking, OSD-Autohide

---

lib/player.py

Shows the post play screen even if playback was stopped instead of ended and the item is considered watched by Plex standards (90%).

Show post play even if playback was stopped

---

lib/windows/seekdialog.py

`lstrip('0')` is used on the time value for the end time. This breaks end times at `00:XX`. Also don't strip the leading zero in case of 24h time format.

Fix end time after midnight not displaying properly

---

lib/_included_packages/plexnet/mediadecisionengine.py
lib/_included_packages/plexnet/plexapp.py
lib/_included_packages/plexnet/plexplayer.py

GHI (If applicable): #224 #214 
- raises the bitrate limit for "Original" quality to 1gbit from 200mbit
- increases the ~~DP-supported~~ transcode-path channel count for DCA from 6 to 8
- re-enables direct play for videos with multiple video streams

Directplay playback fixes

---

lib/_included_packages/plexnet/asyncadapter.py
lib/main.py

- correctly shuts down the socket of `AsyncVerifiedHTTPSConnection` before closing it
- fixes an issue when shutting down the application. `waitForThreads` can end up with an infinite loop as `KillableThread.kill` doesn't do anything

Fix connection handling; shutdown properly with hanging connection

---

lib/_included_packages/plexnet/video.py
lib/windows/episodes.py
lib/windows/preplay.py
lib/windows/subitems.py
lib/windows/videoplayer.py
resources/skins/Main/1080i/script-plex-episodes.xml
resources/skins/Main/1080i/script-plex-pre_play.xml
resources/skins/Main/1080i/script-plex-seasons.xml
resources/skins/Main/1080i/script-plex-video_player.xml

GHI (If applicable): #232 
- adds the unwatched marker and progress indicators for related items in preplay, episodes and postplay windows.
- postplay window: adds progress indicators to onDeck items 
- postplay window: fixes the display of the related items header in certain cases

Add play state info to related items

---

lib/player.py

On my OSMC Kodi it seems like the active video player has the ID 0, not 1 as assumed by `player.py` (this must have changed recently with an OSMC update). This results in resume to not work:
```
16:45:33.145 T:2817839872   ERROR: _________________________________________________________________________________
16:45:33.145 T:2817839872   ERROR: script.plex: ERROR:
16:45:33.145 T:2817839872   ERROR:     Traceback (most recent call last):
16:45:33.145 T:2817839872   ERROR:       File "/home/osmc/.kodi/addons/script.plex/lib/player.py", line 392, in setAudioTrack
16:45:33.145 T:2817839872   ERROR:         currIdx = kodijsonrpc.rpc.Player.GetProperties(playerid=1, properties=['currentaudiostream'])['currentaudiostream']['index']
16:45:33.145 T:2817839872   ERROR: …
```

Fix resume under certain circumstances

---

lib/windows/episodes.py
lib/windows/opener.py
lib/windows/preplay.py

Instead of showing the preplay screen when pressing PLAY on an item from the home screen, play the video directly and show the window afterwards, if necessary.

Auto play quickly from the home hub without showing the actual preplay screen

---

lib/util.py
lib/windows/seekdialog.py

Use Kodi's configured clock format.
- handles 24h, AM/PM and zero-padded-hours natively

Unify clock format

---

lib/windows/episodes.py
lib/windows/home.py
lib/windows/library.py
lib/windows/preplay.py
lib/windows/subitems.py
lib/windows/videoplayer.py

The options header can be opened using ACTION_CONTEXT_MENU, but not be closed the same way. Normally Kodi context menus can be closed again with the same button.

Allow closing of the options header in scrolled views using ACTION_CONTEXT_MENU

---

lib/util.py
lib/windows/episodes.py
lib/windows/home.py
lib/windows/library.py
lib/windows/preplay.py
lib/windows/subitems.py
lib/windows/videoplayer.py
resources/language/English/strings.po
resources/language/German/strings.po
resources/settings.xml

Adds an advanced setting that changes the behaviour of the ACTION_PREVIOUS_MENU to instantly go back instead of showing the menu bar in scrolled views.

Add advanced setting to go back instantly instead of showing the header in scrolled views

---

lib/_included_packages/plexnet/plexapp.py
lib/windows/playersettings.py
lib/windows/settings.py

- fix: manual quality selection is broken right now - only differing resolutions lead to transcoding, as `getMaxBitrate` isn't implemented by the correct interface
- remove super-low unnecessary "video bitrates": 64, 96, 208 kbps

Fix manual quality selection; remove super-low video qualities

---

resources/skins/Main/1080i/script-plex-album.xml
resources/skins/Main/1080i/script-plex-music_current_playlist.xml
resources/skins/Main/1080i/script-plex-playlist.xml
resources/skins/Main/1080i/script-plex-video_current_playlist.xml

- fixes big playlists by visually supporting track numbers > 999
- correctly follows the zoom factor when a playlist item is highlighted
- reversibly removes the currently unused options button of playlist items

Playlists visuals

---

resources/skins/Main/1080i/script-plex-album.xml
resources/skins/Main/1080i/script-plex-dropdown.xml
resources/skins/Main/1080i/script-plex-dropdown_header.xml
resources/skins/Main/1080i/script-plex-listview-16x9-chunked.xml
resources/skins/Main/1080i/script-plex-listview-16x9.xml
resources/skins/Main/1080i/script-plex-listview-square-chunked.xml
resources/skins/Main/1080i/script-plex-listview-square.xml
resources/skins/Main/1080i/script-plex-music_current_playlist.xml
resources/skins/Main/1080i/script-plex-photo.xml
resources/skins/Main/1080i/script-plex-playlist.xml
resources/skins/Main/1080i/script-plex-posters.xml
resources/skins/Main/1080i/script-plex-search.xml
resources/skins/Main/1080i/script-plex-squares.xml

GHI (If applicable): #265
`StringCompare` was already deprecated and removed in Kodi 18.  `String.IsEqual` is its replacement.

Fixed string comparisons to use `String.IsEqual`.

---

lib/util.py

GHI (If applicable): #260
Setting Kodi to Chinese for example currently breaks P4K.

Fix encoding issues when getting System.Time, fixes #260

---

lib/windows/home.py

GHI (If applicable): None
I was seeing cases where hubs were incompletely rendered.  A hub that has 20 items across only shows 1, 2, 3, etc…  Additionally, I was seeing crashes when exiting PfK and the two seemed to be linked.  Putting locks around the concurrent access point between the main thread and the background worker threads appears to have resolved both issues.
PR best viewed by ignoring whitespace.

Put locks around access to UI elements from main and other threads.

---

lib/windows/seekdialog.py
resources/skins/Main/1080i/script-plex-seek_dialog.xml

- don't auto-apply current seek when pressing down on the seekbar (when auto seek is enabled)
- properly reset seek states to avoid issues when switching qualities

Seeking consistency and fixes

---

lib/util.py

Clamps the lower boundary of the progress indicator to 2% to fix "no progress" display issues for items with less than 2% progress.

Fix progress percentage display with progress < 2%

---

lib/_included_packages/plexnet/http.py
lib/_included_packages/plexnet/nowplayingmanager.py
lib/player.py
lib/util.py

GHI (If applicable): #347
- fix missing import error
- unnecessary str decode error
- use xbmcvfs for translatepath (deprecated)
- fix playback with non-auth IPs enabled in PMS settings (#347)

Multiple Kodi 19.1 fixes

---

lib/_included_packages/plexnet/plexplayer.py

Fixes https://github.com/pannal/plex-for-kodi/issues/23
In some cases startOffset is None.
This properly handles this cases. Without this fix,
I've seen errors like `TypeError: '>=' not supported between instances of 'int' and 'NoneType'`.

buildTranscode: ensure startOffset is not None before comparing it

---

lib/player.py

Error:
```
Error Contents: a bytes-like object is required, not 'str'
Traceback (most recent call last):
File "/storage/.kodi/addons/script.plex/lib/windows/kodigui.py", line 105, in onInit
self.onFirstInit()
File "/storage/.kodi/addons/script.plex/lib/windows/musicplayer.py", line 64, in onFirstInit
self.play()
File "/storage/.kodi/addons/script.plex/lib/windows/musicplayer.py", line 152, in play
player.PLAYER.playAudioPlaylist(self.playlist, startpos=list(self.playlist.items()).index(self.track), fanart=fanart)
File "/storage/.kodi/addons/script.plex/lib/player.py", line 858, in playAudioPlaylist
url, li = self.createTrackListItem(track, fanart, index=index)
File "/storage/.kodi/addons/script.plex/lib/player.py", line 874, in createTrackListItem
data = …
```

Fix B64 decode error at playlist creation
