resources/language/Czech/strings.po
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plexinc/plex-for-kodi/75)
=> Add Czech Language

lib/plex.py
created new pull request as per requested.
=> [Friendly Name] change to use the host name of device.

addon.xml, resources/language/French/strings.po
Add french language for the addon
Thanks for your guide ruuk
=> Add french

addon.xml, changelog.txt, lib/windows/home.py
Fix issue with hubs not showing with (newer?) server versions
=> Version bump 0.1.2

lib/windows/home.py, lib/windows/opener.py, lib/windows/preplay.py
=> Auto play episodes, movies and in-progress from home screen by pressing the play button

lib/main.py, lib/util.py, lib/windows/kodigui.py
Probable alternative to #185 - fixes #126
=> Restore the last window when starting the add-on while it is running - #126

resources/language/Portuguese-Brazil/strings.po
Add language Portuguese (Brazil)
=> Language Portuguese-Brazil

lib/_included_packages/plexnet/plexserver.py
=> PR #131 rebased on develop

lib/util.py
Centralizes advanced (non-Plex) settings in one place
=> Centralize advanced settings

lib/windows/currentplaylist.py, lib/windows/library.py
fix usage of mouseYTrans for vertical axis instead of mouseXTrans
=> Fix mouse axis calculation in views

lib/windows/seekdialog.py
=> Add back mouse seek preview; fixes #206

lib/windows/episodes.py, lib/windows/library.py, lib/windows/preplay.py, lib/windows/subitems.py, lib/windows/tracks.py, resources/language/Czech/strings.po, resources/language/English/strings.po, resources/language/French/strings.po, resources/language/German/strings.po, resources/language/Hungarian/strings.po, resources/language/Italian/strings.po, resources/language/Portuguese-Brazil/strings.po, resources/language/Russian/strings.po
Recently the major Plex clients have changed the wording of Unwatched to Unplayed. This does the same.
=> Use Unplayed/Played instead of Unwatched/Watched

lib/main.py
GHI (If applicable): #239
properly log all errors when exiting and ending remaining threads
=> PR #239 logging fix

lib/windows/home.py
GHI (If applicable): #258
This fixes issue #258 by focusing the next best hub on the home screen when the current/previous hub control can't be focused, because it isn't visible anymore.
=> Fix broken home hub focus

lib/util.py, lib/windows/playersettings.py, resources/language/English/strings.po
GHI (If applicable): #276
Leia has a new subtitles menu; the old one in audio settings doesn't exist anymore.
=> Support new subtitles menu in playback for Leia

addon.xml, resources/language/resource.language.es_es/strings.po
New Spanish translation content
=> Spanish translations

resources/language/Portuguese/strings.po
=> Add (European) Portuguese

lib/_included_packages/plexnet/gdm.py, lib/_included_packages/plexnet/plexserver.py, lib/_included_packages/plexnet/signalsmixin.py, lib/backgroundthread.py, lib/main.py, lib/player.py, lib/plex.py, lib/util.py, lib/windows/kodigui.py, lib/windows/seekdialog.py
Fixes GDM issues as well as finally phased-out `xbmc.abortRequested`.
=> Fixes for recent Kodi 19 changes

resources/skins/Main/1080i/script-plex-episodes.xml, resources/skins/Main/1080i/script-plex-home.xml, resources/skins/Main/1080i/script-plex-posters.xml, resources/skins/Main/1080i/script-plex-pre_play.xml, resources/skins/Main/1080i/script-plex-seasons.xml, resources/skins/Main/1080i/script-plex-squares.xml
GHI (If applicable): None
Allow text scrolling on the selected poster/item.
=> Allow text scrolling on selected controls.

lib/_included_packages/plexnet/media.py, lib/_included_packages/plexnet/myplexaccount.py, lib/_included_packages/plexnet/plexlibrary.py, lib/_included_packages/plexnet/plexobjects.py, lib/_included_packages/plexnet/plexserver.py, lib/_included_packages/plexnet/video.py, lib/util.py, lib/windows/seekdialog.py, resources/language/resource.language.en_gb/strings.po, resources/settings.xml, resources/skins/Main/1080i/script-plex-seek_dialog.xml
Adds the support for markers and thus intro skipping for PlexPass enabled users.
=> Add intro skipping

lib/_included_packages/plexnet/video.py
=> Kodi19 filter() usage compat in intro detection

lib/_included_packages/plexnet/plexobjects.py
Work around https://github.com/python/cpython/issues/71587
=> Work around https://github.com/python/cpython/issues/71587
